name: 📌 Create branch when issue is Ready

on:
  issues:
    types:
      - labeled

jobs:
  create-branch:
    if: github.event.label.name == 'bug'
    runs-on: ubuntu-latest
    steps:
      - name: Create branch from test
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const issue = context.payload.issue;
            const title = issue.title;
            const issue_number = issue.number;

            const slug = title
              .toLowerCase()
              .replace(/[^a-z0-9]+/g, '-')
              .replace(/(^-|-$)/g, '');

            const branchName = `feature/${issue_number}-${slug}`;
            const baseBranch = 'test';

            const baseRef = await github.rest.git.getRef({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: `heads/${baseBranch}`,
            });

            await github.rest.git.createRef({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: `refs/heads/${branchName}`,
              sha: baseRef.data.object.sha,
            });

            await github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: issue_number,
              body: `🔧 Automatische branch aangemaakt: \`${branchName}\` vanaf \`${baseBranch}\`.`,
            });
